import Head from "next/head";
import styled from "styled-components";
import DisplaySection from "../container/home/DisplaySection";
import LeaderBoardSection from "../container/home/LeaderBoardSection";
import LocationSection from "../container/home/LocationSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Level-The Beginning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <LeaderBoardSectionContainer>
          <LeaderBoardSection />
        </LeaderBoardSectionContainer>

        <DisplaySectionContainer>
          {/* Middel Section */}
          <DisplaySection />
        </DisplaySectionContainer>

        <LocationSectionContainer>
          {/* Right Section */}
          <LocationSection />
        </LocationSectionContainer>
      </Main>
    </div>
  );
}

const Main = styled.main`
  height: 100vh;
  display: flex;
  flex-direction: row;
  background-color: #234576;
`;

const LeaderBoardSectionContainer = styled.div`
  width: 25%;
`;

const DisplaySectionContainer = styled.div`
  width: 55%;
  display: flex;
  justify-content: center;
  align-items: center;
  background-image: linear-gradient(
      rgba(0, 0, 255, 0.5),
      rgba(35, 69, 118, 0.5)
    ),
    url("/background.jpg");
  background-color: #cccccc; /* Used if the image is unavailable */
  height: 100vh;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
`;

const LocationSectionContainer = styled.div`
  width: 20%;
`;
